# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 09:23
from __future__ import unicode_literals

from django.db import migrations
import ckeditor_uploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_post_add_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
