# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_change_tinymce_to_ckeditor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 11, 13, 43, 15, 400737, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
