# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_access_token', models.CharField(max_length=1000, null=True)),
                ('quickbooks_access_token_expires_in', models.PositiveIntegerField(null=True)),
                ('quickbooks_access_token_updated', models.DateTimeField(null=True)),
                ('quickbooks_refresh_token', models.CharField(max_length=100, null=True)),
                ('quickbooks_refresh_token_expires_in', models.PositiveIntegerField(null=True)),
                ('quickbooks_refresh_token_updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
