# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0001_create_quickbooks_token_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookstoken',
            name='quickbooks_realm_id',
            field=models.IntegerField(null=True),
        ),
    ]
