# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0002_add_realm_id_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksDiscoveryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=100, null=True)),
                ('authorization_endpoint', models.CharField(max_length=100, null=True)),
                ('token_endpoint', models.CharField(max_length=100, null=True)),
                ('userinfo_endpoint', models.CharField(max_length=100, null=True)),
                ('revocation_endpoint', models.CharField(max_length=100, null=True)),
                ('jwks_uri', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
