# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0003_add_quickbooks_discovery_document_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksErrorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=500, null=True)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('successful', models.BooleanField(default=False)),
            ],
        ),
    ]
