# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0004_add_quickbooks_request_errors_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbookserrorrequest',
            name='request',
        ),
        migrations.AddField(
            model_name='quickbookserrorrequest',
            name='request_body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quickbookserrorrequest',
            name='request_headers',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quickbookserrorrequest',
            name='request_type',
            field=models.CharField(choices=[('C', 'Customer'), ('I', 'Invoice'), ('P', 'Payment')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='quickbookserrorrequest',
            name='request_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
