# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0005_add_choices_to_qb_errors_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookserrorrequest',
            name='response_text',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
