# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0006_add_response_text_to_quickbooks_error_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookstoken',
            name='quickbooks_access_token_first_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickbookstoken',
            name='quickbooks_allow_access_again',
            field=models.DateField(default=datetime.date(2018, 8, 2)),
        ),
    ]
