# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_account_1to1_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/photos/'),
        ),
    ]
