# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_account_photo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
