# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_many2many_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_membership',
            field=models.BooleanField(default=False),
        ),
    ]
