# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_change_relation_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_account', to='accounts.Account'),
        ),
    ]
