# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_change_relation_to_onetoone'),
        ('trips', '0007_add_trip_date_and_minor_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='trips',
            field=models.ManyToManyField(related_name='account', to='trips.TripDate'),
        ),
    ]
