# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_change_tinymce_to_ckeditor'),
        ('accounts', '0009_change_user_relation_to_tripdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=50)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_trip_subscription', to='trips.TripDate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_account_subscription', to='accounts.Account')),
            ],
        ),
    ]
