# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_create_stripe_subscriptions_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePlanNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=70)),
                ('plan_name', models.CharField(max_length=70)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
