# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_relation_from_stripe_subscriptions_to_stripe_plans_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripesubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_plan_subscription', to='accounts.StripePlanNames'),
        ),
    ]
