# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_null_true_to_stripe_subcscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstripesubscription',
            name='payments',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
