# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_payments_field_stripesubscriptions_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
