# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_points_field_to_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuickBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quickbooks_account', to='accounts.Account')),
            ],
        ),
    ]
