# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_user_quickbooks_account_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstripesubscription',
            name='quickbooks_invoice_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
