# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 15:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_add_excursions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='slug',
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='description'),
            preserve_default=False,
        ),
    ]
