# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_change_ckeditor_to_tinymce'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(blank=True)),
                ('departure', models.DateTimeField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.AlterField(
            model_name='tripimage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_image', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_date', to='trips.Trip'),
        ),
    ]
