# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_add_trip_date_and_minor_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdate',
            name='arrival',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tripdate',
            name='departure',
            field=models.DateField(blank=True),
        ),
    ]
