# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_change_trip_datetime_to_datefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='trip',
        ),
        migrations.AddField(
            model_name='excursion',
            name='trip',
            field=models.ManyToManyField(related_name='excursions', to='trips.TripDate'),
        ),
    ]
