# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_excustions_manytomany_tripdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
            preserve_default=False,
        ),
    ]
