# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 12:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_add_price_to_excursions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
