# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_change_tinymce_to_ckeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='itinerary_days',
            field=models.PositiveSmallIntegerField(blank=True, default=9),
            preserve_default=False,
        ),
    ]
