# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_add_itinerary_days_to_trip_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFlightCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_cost', to='trips.Trip')),
            ],
        ),
    ]
