# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_add_trip_flight_cost_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='trips/images/'),
        ),
    ]
