# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_add_image_thumbnail_to_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdate',
            name='image_thumbnail',
            field=models.ImageField(default='none/image_thumbnail.jpg', upload_to='trips/images/'),
        ),
    ]
