# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_add_default_image_to_trip_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='image_main',
            field=models.ImageField(default='none/image_main.jpg', upload_to='trips/images/'),
        ),
    ]
