# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_add_main_image_to_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdate',
            name='image_main',
            field=models.ImageField(default='trip_defaults/image_main.jpg', upload_to='trips/images/'),
        ),
        migrations.AlterField(
            model_name='tripdate',
            name='image_thumbnail',
            field=models.ImageField(default='trip_defaults/image_thumbnail.jpg', upload_to='trips/images/'),
        ),
    ]
