# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_change_defaults_image_urls_for_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripimage',
            name='trip',
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
